services:
  web:
    build: .
    image: web:latest
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: nginx-axietreasury-local
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80" 
    depends_on:
      - web

